import {
  IconAlertTriangle,
  IconArchive,
  IconBell,
  IconBox,
  IconCalendar,
  IconCategory,
  IconCheck,
  IconChevronLeft,
  IconCircleCheck,
  IconClipboardList,
  IconCopy,
  IconCrown,
  IconCurrencyDong,
  IconDiamond,
  IconEdit,
  IconFileText,
  IconFlame,
  IconFolder,
  IconGift,
  IconHeadset,
  IconHelp,
  IconLayoutDashboard,
  IconLayoutSidebar,
  IconLock,
  IconLogout,
  IconMenu2,
  IconMessage,
  IconNeedle,
  IconPackage,
  IconPalette,
  IconPaperclip,
  IconPlayerPause,
  IconPlayerPlay,
  IconRefresh,
  IconRobot,
  IconSearch,
  IconSend,
  IconSettings,
  IconShoppingBag,
  IconShoppingCart,
  IconSparkles,
  IconStar,
  IconTag,
  IconTicket,
  IconTrash,
  IconTrendingUp,
  IconTruck,
  IconUser,
  IconUsers,
  IconX,
} from '@tabler/icons-react';

const stroke = 1.5;

/** Default stroke matches the shadcn dashboard Tabler set. */
const withDefaults = (Icon) => {
  const Wrapped = ({ size = 20, stroke: strokeWidth = stroke, className = '', ...props }) => (
    <Icon size={size} stroke={strokeWidth} className={`tb-icon ${className}`.trim()} {...props} />
  );
  Wrapped.displayName = Icon.displayName || Icon.name;
  return Wrapped;
};

export const Icons = {
  dashboard: withDefaults(IconLayoutDashboard),
  product: withDefaults(IconBox),
  category: withDefaults(IconCategory),
  orders: withDefaults(IconClipboardList),
  promotion: withDefaults(IconTicket),
  users: withDefaults(IconUsers),
  chat: withDefaults(IconMessage),
  faq: withDefaults(IconHelp),
  blog: withDefaults(IconFileText),
  account: withDefaults(IconUser),
  settings: withDefaults(IconSettings),
  menu: withDefaults(IconMenu2),
  panelLeft: withDefaults(IconLayoutSidebar),
  cart: withDefaults(IconShoppingCart),
  bag: withDefaults(IconShoppingBag),
  notification: withDefaults(IconBell),
  user: withDefaults(IconUser),
  check: withDefaults(IconCheck),
  circleCheck: withDefaults(IconCircleCheck),
  close: withDefaults(IconX),
  warning: withDefaults(IconAlertTriangle),
  speaker: withDefaults(IconBell),
  logout: withDefaults(IconLogout),
  lock: withDefaults(IconLock),
  gift: withDefaults(IconGift),
  ticket: withDefaults(IconTicket),
  cash: withDefaults(IconCurrencyDong),
  package: withDefaults(IconPackage),
  folder: withDefaults(IconFolder),
  tag: withDefaults(IconTag),
  refresh: withDefaults(IconRefresh),
  edit: withDefaults(IconEdit),
  trash: withDefaults(IconTrash),
  archive: withDefaults(IconArchive),
  copy: withDefaults(IconCopy),
  send: withDefaults(IconSend),
  paperclip: withDefaults(IconPaperclip),
  sparkles: withDefaults(IconSparkles),
  robot: withDefaults(IconRobot),
  headset: withDefaults(IconHeadset),
  search: withDefaults(IconSearch),
  calendar: withDefaults(IconCalendar),
  flame: withDefaults(IconFlame),
  star: withDefaults(IconStar),
  diamond: withDefaults(IconDiamond),
  palette: withDefaults(IconPalette),
  needle: withDefaults(IconNeedle),
  trendingUp: withDefaults(IconTrendingUp),
  pause: withDefaults(IconPlayerPause),
  play: withDefaults(IconPlayerPlay),
  chevronLeft: withDefaults(IconChevronLeft),
  crown: withDefaults(IconCrown),
  truck: withDefaults(IconTruck),
};
